;	DME assembly file, generated by lcc 4.2

 ; INT_MAX: ffffffff;	.global _kprintfold
;	.code
_kprintfold:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	stw	-2(bp),r0
	la16	r4,L3
	br.r r4
L2:
	ldw	r4,-2(bp)
	ldw	r3,4(bp)
	add	r4,r4,r3
	ldb	r4,r0(r4)
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
	ldw	r4,-2(bp)
	addi	r4,r4,1
	stw	-2(bp),r4
L3:
	ldw	r4,-2(bp)
	ldw	r3,4(bp)
	add	r4,r4,r3
	ldb	r4,r0(r4)
	skip.eq r4,r0
	br L2
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.global _kprintf
_kprintf:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 8
	sub	sp, sp, r4
	ldi	r4, 6
	add	r4, r4, bp
	stw	-8(bp),r4
	stw	-6(bp),r0
	la16	r4,L10
	br.r r4
L7:
	ldw	r4,-2(bp)
	ld16	r3, 37
	skip.ne	r4,r3
	br	L11
	ldw	r4,-2(bp)
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
	la16	r4,L8
	br.r r4
L11:
	ldw	r4,-6(bp)
	addi	r4,r4,1
	stw	-6(bp),r4
	ldw	r3,4(bp)
	add	r4,r4,r3
	ldb	r4,r0(r4)
	ld16	r3, 255
	and	r4,r4,r3
	stw	-2(bp),r4
	ldw	r4,-2(bp)
	skip.eq r4,r0
	br L13
	la16	r4,L9
	br.r r4
L13:
	ldw	r4,-2(bp)
	ld16	r3, 104
	skip.ne	r4,r3
	br	L18
	skip.lte	r4,r3
	br	L29
L28:
	ldw	r4,-2(bp)
	ld16	r3, 37
	skip.ne	r4,r3
	br	L27
	skip.gte	r4,r3
	br	L15
L30:
	ldw	r4,-2(bp)
	ld16	r3, 100
	skip.ne	r4,r3
	br	L17
	la16	r4,L15
	br.r r4
L29:
	ldw	r4,-2(bp)
	ld16	r3, 112
	skip.ne	r4,r3
	br	L18
	ld16	r2, 115
	skip.ne	r4,r2
	br	L19
	skip.gte	r4,r3
	br	L15
L31:
	ldw	r4,-2(bp)
	ld16	r3, 120
	skip.ne	r4,r3
	br	L18
	la16	r4,L15
	br.r r4
L17:
	ld16	r4, 1
	push	r4
	ld16	r4, 10
	push	r4
	ldw	r4,-8(bp)
	addi	r3,r4,2
	stw	-8(bp),r3
	ldw	r4,r0(r4)
	push	r4
	la16	r2,_printint ; jaddr
	addi	r1,pc,2
	br.r	r2
	la16	r4,L16
	br.r r4
L18:
	push	r0
	ld16	r4, 16
	push	r4
	ldw	r4,-8(bp)
	addi	r3,r4,2
	stw	-8(bp),r3
	ldw	r4,r0(r4)
	push	r4
	la16	r2,_printint ; jaddr
	addi	r1,pc,2
	br.r	r2
	la16	r4,L16
	br.r r4
L19:
	ldw	r4,-8(bp)
	addi	r3,r4,2
	stw	-8(bp),r3
	ldw	r4,r0(r4)
	stw	-4(bp),r4
	skip.eq r4,r0
	br L26
	la16	r4,L22
	stw	-4(bp),r4
	la16	r4,L26
	br.r r4
L23:
	ldw	r4,-4(bp)
	ldb	r4,r0(r4)
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
L24:
	ldw	r4,-4(bp)
	addi	r4,r4,1
	stw	-4(bp),r4
L26:
	ldw	r4,-4(bp)
	ldb	r4,r0(r4)
	skip.eq r4,r0
	br L23
	la16	r4,L16
	br.r r4
L27:
	ld16	r4, 37
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
	la16	r4,L16
	br.r r4
L15:
	ld16	r4, 37
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
	ldw	r4,-2(bp)
	push	r4
	la16	r2,_putc ; jaddr
	addi	r1,pc,2
	br.r	r2
L16:
L8:
	ldw	r4,-6(bp)
	addi	r4,r4,1
	stw	-6(bp),r4
L10:
	ldw	r4,-6(bp)
	ldw	r3,4(bp)
	add	r4,r4,r3
	ldb	r4,r0(r4)
	ld16	r3, 255
	and	r4,r4,r3
	stw	-2(bp),r4
	skip.eq r4,r0
	br L7
L9:
L5:
	mov	sp, bp
	pop	bp
	pop	pc

;	.extern _printint
;	.extern _putc
	.data
L22:
	defstr "(null)"
;	.end
