;	DME assembly file, generated by lcc 4.2

;	.global _kmain
;	.code
_kmain:
	push	r1
	push	bp
	mov	bp, sp
	la16	r4,L2
	push	r4
	addi	r1,pc,2
	br	_kprintf ; jaddr
	mov	r1,r0
L1:
	pop	bp
	pop	pc

;	.extern _kprintf
	.data
L2:
	defstr "DME OS.."
;	.end
