;	DME assembly file, generated by lcc 4.2

include(macro.h)

	.data 0x1000
;	.global _x
_x:
defw 0x2
;	.global _y
_y:
defw 0x3
;	.global _main
;	.code
_main:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	la16	r4,_x
	ldw	r4,r0(r4)
	la16	r3,_y
	ldw	r3,r0(r3)
MULT16(r1,r4,r3)
	stw	-2(bp),r1
	ldw	r1,-2(bp)
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end
