;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x2000 and branches to main
	ld16	r1, 0x2000
	mov	sp, r1
	addi	r1, pc, 2
	br	_main
	hlt


;	.global _main
;	.code
_main:
	push	r1
	push	bp
	mov	bp, sp
	ld16	r4, 101
	push	r4
	addi	r1,pc,2
	br	_putc ; jaddr
	mov	r1,r0
L1:
	pop	bp
	pop	pc

;	.extern _putc
;	.end
