;	DME assembly file, generated by lcc 4.2

 ; INT_MAX: ffffffff

	.data 0x1000
;	.global _sdcmd
_sdcmd:
defw 0xffa2
;	.global _sddata
_sddata:
defw 0xffa6
;	.global _sdfifo0H
_sdfifo0H:
defw 0xffa8
;	.global _sdfifo0L
_sdfifo0L:
defw 0xffaa
;	.global _main
;	.code
_main:
la16 r1, 0x2000
mov sp, r1
	push	r1
	push	bp
	mov	bp, sp
	la16	r4,_bf+4
	ld16	r3, 47
	stw	r0(r4),r3
	la16	r4,_bf
	push	r4
	la16	r4,_bf+4
	ldw	r4,r0(r4)
	push	r4
	la16	r2,_sdreadasm
	addi	r1,pc,2
	br.r	r2
	ldi	r2,4
	add	sp,sp,r2
	hlt
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.global _sdread
_sdreadasm:
	push	r1
	push	bp
	mov	bp, sp
	ldw r1, 4(bp) ; blockno
	ldw r2, 6(bp) ; buf ptr
	brk
	la16	r4,0xffa6
	stw	r0(r4),r1

	la16	r4,0xffa2
	ld16	r3, 0x8851
	stw	r0(r4),r3

	la16 r3, 0xffa8
	la16 r4, 0xffaa
L4:
	ldw r1, r0(r3)
	stw r0(r2), r1
	addi r2, r2, 2

	ldw r1, r0(r4)
	stw r0(r2), r1
	addi r2, r2, 2

	la16 r1, 512
	skip.gte r2, r1
	br L4

L3:
	mov	sp, bp
	pop	bp
	pop	pc
;	.extern _halt
;	.extern _sdreadasm
	.bss
;	.global _bf
_bf:
	defs 522
;	.extern _sdread
;	.end
