;	DME assembly file, generated by lcc 4.2

;  temp boiler plate puts SP at 0x2000 and branches to main
	ld16	r1, 0x2000
	mov	sp, r1
	addi	r1, pc, 2
	br	_main
	hlt


;	.global _init
;	.code
_main:
	push	r1
	push	bp
	mov	bp, sp
	ldi	r4, 2
	sub	sp, sp, r4
	ld16	r4, 0x1000
	stw	-2(bp),r4
	ldw	r4,-2(bp)
	addi	r4,r4,1
	stb	r0(r4),r0
	ldw	r4,-2(bp)
	ld16	r3, 3
	add	r4,r4,r3
	ld16	r3, 128
	stb	r0(r4),r3
	ldw	r4,-2(bp)
	ld16	r3, 50
	stb	r0(r4),r3
	ldw	r4,-2(bp)
	addi	r4,r4,1
	stb	r0(r4),r0
	ldw	r4,-2(bp)
	ld16	r3, 3
	add	r4,r4,r3
	ld16	r3, 3
	stb	r0(r4),r3
L1:
	mov	sp, bp
	pop	bp
	pop	pc

;	.end
